Support setting recommended updates
PowerShell/xWindowsUpdate pull request #31
Opened 2016-12-29 00:46 UTC by johnf

2016-12-29 00:46 UTC, msftclas commented
Hi __@johnf__, I'm your friendly neighborhood Microsoft Pull Request Bot (You can call me MSBOT). Thanks for your contribution!
    <span>You've already signed the contribution license agreement. Thanks!</span>
        <span>We will now validate the agreement and then real humans will evaluate your PR.</span>

TTYL, MSBOT;

2017-02-05 01:43 UTC, TravisEz13 requested changes

2017-02-05 01:43 UTC, TravisEz13 commented on README.md
> +* **RecommendedUpdates**: Whether to include Recommended updates (default false).
This description is not accurate.  Please update the description.  Please include the impact on `Optional` and `Important` updates.

2017-02-05 01:46 UTC, TravisEz13 commented
Additionally, the CLA must be signed.  
If you need help understanding the impact of the change to write the description.  You can find my contact information in my profile.

2017-12-20 21:55 UTC, johnf commented
Hi @TravisEz13 could you take another look at this? I've updated the descriptions and variable names in the code

2017-12-20 22:02 UTC, TravisEz13 approved these changes

2017-12-20 22:03 UTC, TravisEz13 commented
My approval is for your changes.  The tests need to be fixed.

2018-05-07 11:50 UTC, johlju commented
@johnf Are you able to work on this issue so we can bring this to the finish line?

2018-05-23 09:48 UTC, johlju commented
Labeling this PR as abandoned since it has gone 14 days or more since the last update. An abandoned PR can be continued by another contributor. The abandoned label will be removed if work on the PR is taken up again.

2018-05-27 04:52 UTC, johnf commented
OK Tests are now working. Although they are currently broken for the project.

Note the commit in ```appveyor.yml``` is a hack to make the tests pass.

The last commit to PowerShell/DscResource.Tests#230 is breaking the tests. See https://ci.appveyor.com/project/PowerShell/xwindowsupdate/build/2.5.193.0 for an example. Not sure if problem is on our end or theirs.

2018-05-28 10:42 UTC, johlju commented
Sorry about the trouble with the tests! I made review comments to resolved that without reverting to an older commit.

Do you have a chance to resolve these review comments?

---

Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[appveyor.yml, line 7 at r3](https://reviewable.io/reviews/powershell/xwindowsupdate/31#-LDaC_BU-4PdST5zFhtA:-LDaC_BV3QA5tl4FdoRh:b-cx1put) ([raw file](https://github.com/powershell/xwindowsupdate/blob/a54177c451953f5ca3f05103ca2e12671ebe75d1/appveyor.yml#L7)):*
> ```YAML
> install: 
>     - git clone https://github.com/PowerShell/DscResource.Tests
>     - cd DscResource.Tests
> ```

For line 7-9 should be able to be removed if resolving the other comments for this file.

---

*[appveyor.yml, line 12 at r3](https://reviewable.io/reviews/powershell/xwindowsupdate/31#-LDaCXFJAW4eMBOgD9YZ:-LDaCXFJAW4eMBOgD9Y_:bz8m76) ([raw file](https://github.com/powershell/xwindowsupdate/blob/a54177c451953f5ca3f05103ca2e12671ebe75d1/appveyor.yml#L12)):*
> ```YAML
>     - ps: |
>         $moduleName = 'xWindowsUpdate'
>         $mainModuleFolder = ".\"
> ```

This should not be needed, see previous comment.

---

*[appveyor.yml, line 30 at r3](https://reviewable.io/reviews/powershell/xwindowsupdate/31#-LDaCKsPA4biDu5e_6eS:-LDaCKsPA4biDu5e_6eT:bbxn1tt) ([raw file](https://github.com/powershell/xwindowsupdate/blob/a54177c451953f5ca3f05103ca2e12671ebe75d1/appveyor.yml#L30)):*
> ```YAML
>         Invoke-AppveyorTestScriptTask `
>             -Type 'Default' `
>             -MainModulePath $mainModuleFolder `
> ```

This parameter should not be here. It is not used when `Type` is `'Default'`.

---

*[README.md, line 31 at r1](https://reviewable.io/reviews/powershell/xwindowsupdate/31#-K_71oeXRerLRzcSeLs8-r1-31:-LDaET1F742z4nPZ5ktm:biyidcp) ([raw file](https://github.com/powershell/xwindowsupdate/blob/9a538cf4654da8443e470a3eb1383ed0d9c42b7c/README.md#L31)):*
<details><summary><i>Previously, TravisEz13 (Travis Plunk) wrote…</i></summary><blockquote>

This description is not accurate.  Please update the description.  Please include the impact on `Optional` and `Important` updates.
</blockquote></details>

This is not part of the code that is changed in this PR, so issue #47 has been submitted for his instead. 

---

*[DscResources/MSFT_xWindowsUpdateAgent/MSFT_xWindowsUpdateAgent.psm1, line 179 at r3](https://reviewable.io/reviews/powershell/xwindowsupdate/31#-LDaJ_8Q3Yr470CvWd0Z:-LDaJ_8Q3Yr470CvWd0_:b-c0evll) ([raw file](https://github.com/powershell/xwindowsupdate/blob/a54177c451953f5ca3f05103ca2e12671ebe75d1/DscResources/MSFT_xWindowsUpdateAgent/MSFT_xWindowsUpdateAgent.psm1#L179)):*
> ```PowerShell
> }
> 
> function Get-WuaAuIncludeRecommendedUpdates
> ```

Please add comment-based help to this helper function, at least `.SYNOPSIS`.

---

*[DscResources/MSFT_xWindowsUpdateAgent/MSFT_xWindowsUpdateAgent.psm1, line 181 at r3](https://reviewable.io/reviews/powershell/xwindowsupdate/31#-LDaFwPCD9Toji_paFOU:-LDaFwPCD9Toji_paFOV:b-51et0q) ([raw file](https://github.com/powershell/xwindowsupdate/blob/a54177c451953f5ca3f05103ca2e12671ebe75d1/DscResources/MSFT_xWindowsUpdateAgent/MSFT_xWindowsUpdateAgent.psm1#L181)):*
> ```
> -tryBlock
> ```

`-TryBlock` (upper 'T')

---

*[DscResources/MSFT_xWindowsUpdateAgent/MSFT_xWindowsUpdateAgent.psm1, line 250 at r3](https://reviewable.io/reviews/powershell/xwindowsupdate/31#-LDaJhDZ4yyfxYeIMTbd:-LDaJhDZ4yyfxYeIMTbe:b-gek8d5) ([raw file](https://github.com/powershell/xwindowsupdate/blob/a54177c451953f5ca3f05103ca2e12671ebe75d1/DscResources/MSFT_xWindowsUpdateAgent/MSFT_xWindowsUpdateAgent.psm1#L250)):*
> ```PowerShell
> }
> 
> function Set-WuaAuIncludeRecommendedUpdates
> ```

Please add comment-based help to this helper function, at least `.SYNOPSIS` and `.PARAMETER`.

---

*[DscResources/MSFT_xWindowsUpdateAgent/MSFT_xWindowsUpdateAgent.psm1, line 252 at r3](https://reviewable.io/reviews/powershell/xwindowsupdate/31#-LDaG0yj6Y8BsyqawkUb:-LDaG0yj6Y8BsyqawkUc:b-z4dqwg) ([raw file](https://github.com/powershell/xwindowsupdate/blob/a54177c451953f5ca3f05103ca2e12671ebe75d1/DscResources/MSFT_xWindowsUpdateAgent/MSFT_xWindowsUpdateAgent.psm1#L252)):*
> ```PowerShell
> function Set-WuaAuIncludeRecommendedUpdates
> {
>     param(
> ```

parenthesis should be on a separate row.

---

*[DscResources/MSFT_xWindowsUpdateAgent/MSFT_xWindowsUpdateAgent.psm1, line 253 at r3](https://reviewable.io/reviews/powershell/xwindowsupdate/31#-LDaG6e482dDVEalWVNA:-LDaG6e482dDVEalWVNB:b-gdnlm7) ([raw file](https://github.com/powershell/xwindowsupdate/blob/a54177c451953f5ca3f05103ca2e12671ebe75d1/DscResources/MSFT_xWindowsUpdateAgent/MSFT_xWindowsUpdateAgent.psm1#L253)):*
> ```
> [bool]
> ```

`[Boolean]`

---

*[DscResources/MSFT_xWindowsUpdateAgent/MSFT_xWindowsUpdateAgent.psm1, line 367 at r3](https://reviewable.io/reviews/powershell/xwindowsupdate/31#-LDaG8qY2TUvbQA8ttCw:-LDaG8qY2TUvbQA8ttCx:b-31kvn1) ([raw file](https://github.com/powershell/xwindowsupdate/blob/a54177c451953f5ca3f05103ca2e12671ebe75d1/DscResources/MSFT_xWindowsUpdateAgent/MSFT_xWindowsUpdateAgent.psm1#L367)):*
> ```
> [bool]
> ```

`[Boolean]`. Throughout this new parameter.

---

*[DscResources/MSFT_xWindowsUpdateAgent/MSFT_xWindowsUpdateAgent.psm1, line 474 at r3](https://reviewable.io/reviews/powershell/xwindowsupdate/31#-LDaIXwO2wzG6jGuHylN:-LDaIXwO2wzG6jGuHylO:b-34ygjv) ([raw file](https://github.com/powershell/xwindowsupdate/blob/a54177c451953f5ca3f05103ca2e12671ebe75d1/DscResources/MSFT_xWindowsUpdateAgent/MSFT_xWindowsUpdateAgent.psm1#L474)):*
> ```PowerShell
>     Write-Verbose "notifications compliant: $notificationCompliant"
>     $SourceCompliant = (!$Source -or $Source -eq $Get.Source)
>     $recommendedUpdatesCompliant = (!$IncludeRecommendedUpdates -or $IncludeRecommendedUpdates -eq $Get.IncludeRecommendedUpdates)
> ```

See comment in Test-TargetResource for this evaluation.

---

*[DscResources/MSFT_xWindowsUpdateAgent/MSFT_xWindowsUpdateAgent.psm1, line 528 at r3](https://reviewable.io/reviews/powershell/xwindowsupdate/31#-LDaIxo_8oZ6DZwm26zY:-LDaIxo_8oZ6DZwm26zZ:by212aj) ([raw file](https://github.com/powershell/xwindowsupdate/blob/a54177c451953f5ca3f05103ca2e12671ebe75d1/DscResources/MSFT_xWindowsUpdateAgent/MSFT_xWindowsUpdateAgent.psm1#L528)):*
> ```
> $PSCmdlet.ShouldProcess(
> ```

We should not use ShouldProcess in DSC resources. This can be removed (see there are more of these, but let's not add more to remove to the backlog) :slightly_smiling_face: 

---

*[DscResources/MSFT_xWindowsUpdateAgent/MSFT_xWindowsUpdateAgent.psm1, line 532 at r3](https://reviewable.io/reviews/powershell/xwindowsupdate/31#-LDaIgVf2efpAIOkQo7A:-LDaIgVf2efpAIOkQo7B:b-kvbxkp) ([raw file](https://github.com/powershell/xwindowsupdate/blob/a54177c451953f5ca3f05103ca2e12671ebe75d1/DscResources/MSFT_xWindowsUpdateAgent/MSFT_xWindowsUpdateAgent.psm1#L532)):*
> ```PowerShell
>                 Try
>                 {
>                     #TODO verify that group policy is not overriding this settings
> ```

Is this todo comment something that needs to resolved prior to merge, or as a separate issue?

---

*[DscResources/MSFT_xWindowsUpdateAgent/MSFT_xWindowsUpdateAgent.psm1, line 539 at r3](https://reviewable.io/reviews/powershell/xwindowsupdate/31#-LDaJEW0-U8nJRN_IJ9U:-LDaJEW0-U8nJRN_IJ9V:b-wak1df) ([raw file](https://github.com/powershell/xwindowsupdate/blob/a54177c451953f5ca3f05103ca2e12671ebe75d1/DscResources/MSFT_xWindowsUpdateAgent/MSFT_xWindowsUpdateAgent.psm1#L539)):*
> ```PowerShell
>                 {
>                     $ErrorMsg = $_.Exception.Message
>                     Write-Verbose $ErrorMsg
> ```

Shouldn't we throw if there are a problem here? 

---

*[DscResources/MSFT_xWindowsUpdateAgent/MSFT_xWindowsUpdateAgent.psm1, line 600 at r3](https://reviewable.io/reviews/powershell/xwindowsupdate/31#-LDaHYZS5xldASiJnC4f:-LDaHYZS5xldASiJnC4g:b-mwtoya) ([raw file](https://github.com/powershell/xwindo [...]

2018-05-28 11:08 UTC, johlju commented
I just merged a fix for the appveyor.yml.

---

Review status: all files reviewed at latest revision, 15 unresolved discussions, some commit checks failed.

---

*[appveyor.yml, line 7 at r3](https://reviewable.io/reviews/powershell/xwindowsupdate/31#-LDaQY6AErhiTgLNEc4t:-LDaQY6AErhiTgLNEc4u:bu7r7ve) ([raw file](https://github.com/powershell/xwindowsupdate/blob/a54177c451953f5ca3f05103ca2e12671ebe75d1/appveyor.yml#L7)):*
> ```YAML
> install: 
>     - git clone https://github.com/PowerShell/DscResource.Tests
>     - cd DscResource.Tests
> ```

 Line 7-9 should not be necessary now.

---


*Comments from [Reviewable](https://reviewable.io/reviews/powershell/xwindowsupdate/31#-:-LDaQbOl2ideBWIXc_3f:b-tj2bpw)*
<!-- Sent from Reviewable.io -->

2018-06-04 07:18 UTC, johnf commented
@johlju I don't think I can help much further on this commit. I implemented this code at a previous role where I was doing a small amount of windows automation.
I no longer have access to any systems to do any testing and what I've got so far is stretching my non-existent Powershell knowledge.
Just to make the changes I did this time around I was using appveyor to effectively run the code for me.

Hopefully someone else can pick up the rest of the changes.

2018-06-04 09:15 UTC, johlju commented
@johnf Thanks for the work, and thank you for the information! I will label this as abandoned so that someone else in the community can pick this up!

2021-11-27 23:12 UTC, closed without merging